install.packages("reshape", dependencies=T, lib=.libPaths()[1])
install.packages("reshape2", dependencies=T, lib=.libPaths()[1])
install.packages("dtplyr", dependencies=T, lib=.libPaths()[1])
install.packages("data.table", dependencies=T, lib=.libPaths()[1])
dyn.load('/usr/lib/oracle/21/client64/lib/libclntsh.so.21.1')
install.packages("DBI", dependencies=T, lib=.libPaths()[1])
install.packages("ROracle", dependencies = TRUE, lib=.libPaths()[1], repos='http://cran.mirrors.hoobly.com', configure.args=" --with-oci-inc=/usr/include/oracle/21/client64 --with-oci-lib=/usr/lib/oracle/21/client64/lib")
install.packages("lubridate", dependencies=T, lib=.libPaths()[1])
install.packages("snow", dependencies=T, lib=.libPaths()[1])
urlPackage <- "https://cran.r-project.org/src/contrib/Archive/randomForest/randomForest_4.6-12.tar.gz"
install.packages(urlPackage, repos=NULL, type="source") 
install.packages("foreach", dependencies=T, lib=.libPaths()[1])
install.packages("doSNOW", dependencies=T, lib=.libPaths()[1])
install.packages("plyr", dependencies=T, lib=.libPaths()[1])
install.packages("nnet", dependencies=T, lib=.libPaths()[1])
install.packages("mlogit", dependencies=T, lib=.libPaths()[1])
install.packages("sqldf", dependencies=T, lib=.libPaths()[1])
install.packages("dplyr", dependencies=T, lib=.libPaths()[1])
install.packages("rJava", dependencies=T, lib=.libPaths()[1])
install.packages("xlsx", dependencies=T, lib=.libPaths()[1])
install.packages("lubridate", dependencies=T, lib=.libPaths()[1])
install.packages("marima", dependencies=T, lib=.libPaths()[1])
install.packages("forecast", dependencies=T, lib=.libPaths()[1])
install.packages("arules", dependencies=T, lib=.libPaths()[1])
install.packages("bigmemory", dependencies=T, lib=.libPaths()[1])
install.packages("mlr", dependencies=T, lib=.libPaths()[1])
install.packages("miscTools", dependencies=T, lib=.libPaths()[1])
install.packages("stringdist", dependencies=T, lib=.libPaths()[1])
install.packages("stringr", dependencies=T, lib=.libPaths()[1])
install.packages("devtools", dependencies=T, lib=.libPaths()[1])
install.packages("fasttime", dependencies=T, lib=.libPaths()[1])
install.packages("imputeTS", dependencies=T, lib=.libPaths()[1])
install.packages("tsoutliers")
require(devtools) # Install older version of modeest as new version is not compatible with parts of our code.
install_version("modeest", version = "2.1", repos = "http://cran.us.r-project.org")
randomForestURL <- "https://cran.r-project.org/src/contrib/Archive/randomForest/randomForest_4.6-14.tar.gz"
install.packages(randomForestURL, repos=NULL, type="source", lib=.libPaths()[1])
rowrURL <- "https://cran.microsoft.com/snapshot/2015-07-29/src/contrib/rowr_1.1.2.tar.gz"
install.packages(rowrURL, repos=NULL, type="source", lib=.libPaths()[1]) 
 
